### ISSUE TITLE
preventing reset issues

### ISSUE THREAD

**Issue by computron** [Matgenix/jobflow-remote#102]
To prevent unintentional resets of production database, I suggest the user needs to type the name of the project (not just "y") in order to reset if the project has more than a handful of Flows in it.

**Comment by gpetretto** [comment]
At the moment there is an additional safe guard. When running `jf admin reset` there is also this option:

```
--max     -m      INTEGER  The database will be reset only if the number of Flows is lower than the specified limit. 0 means no limit [default: 25]
```

so this means that if there are more than 25 flows in the DB the reset will be refused, even if the confirmation (y) is given. In that case the user will need to pass a suitable `-m` option (e.g. `-m 0`) to really reset the DB.

Switching to ask the project name for confirmation could be a good option replacing the `-m`. Do you think it is worth changing, or was it just to have an additional safe guard against resetting large databases?
