### ISSUE TITLE
SUGGESTION: Add an example for querying results from the database

### ISSUE THREAD

**Issue by naik-aakash** [Matgenix/jobflow-remote#115]
Hi @gpetretto, I noticed that the documentation does not currently have any information about how to query information about the finished jobs using the Python API. (Example: User wants to back up only some particular type of calculation files or organize calculation files in some specific directory structure)

I would happily raise a PR with a small example code snippet if desired

**Comment by davidwaroquiers** [comment]
Hi @naik-aakash ,

Sure, that would be helpful! See maybe with @gpetretto where this could/should be added.

**Comment by naik-aakash** [comment]
Great!

**Comment by naik-aakash** [comment]
Hi @davidwaroquiers and @gpetretto, I see there is already info added to the documentation on how to do this here.

https://github.com/Matgenix/jobflow-remote/blob/967e7c512f230105b1a82c2227fb101d8d4acb3d/doc/source/user/quickstart.rst?plain=1#L187. 

I was thinking the something similar, so am closing this issue for now.
