### ISSUE TITLE
a suggestion to improve the documentation

### ISSUE THREAD

**Issue by QuantumChemist** [Matgenix/jobflow-remote#143]
Hey 😃 

I have a small suggestion for the jobflow-remote documentation.
Maybe here https://matgenix.github.io/jobflow-remote/user/tuning.html#resources you could put hyperlinks to 

https://matgenix.github.io/qtoolkit/api/qtoolkit.io.slurm.html and
https://matgenix.github.io/qtoolkit/api/qtoolkit.io.pbs.html

so that the user can easier look up what kind of command-keywords can be passed in the resource dictionary.

If you agree, I could do that in a PR.

**Comment by gpetretto** [comment]
Hi @QuantumChemist,

indeed this would be helpful. Feel free to open a PR. Thanks!
