### ISSUE TITLE
Correct setup of jfremote config project.yaml file for nested gateways

### ISSUE THREAD

**Issue by QuantumChemist** [Matgenix/jobflow-remote#153]
Hi 😃 

I'm trying to set up jobflow-remote for @DervinSun on his machines using the interactive branch, but unlike my case he has to use a nested gateway. We cannot really figure out how the project.yaml file has to be set up in that case. Could you give me an example for that?

This is a generalized version of the file we are working with:

```bash
name: test_project
base_dir: /home/username/.jfremote/test_project
tmp_dir: /home/username/.jfremote/test_project/tmp
log_dir: /home/username/.jfremote/test_project/log
daemon_dir: /home/username/.jfremote/test_project/daemon
log_level: debug
runner:
  delay_checkout: 30
  delay_check_run_status: 30
  delay_advance_status: 30
  delay_refresh_limited: 600
  delay_update_batch: 60
  lock_timeout: 86400
  delete_tmp_folder: true
  max_step_attempts: 3
  delta_retry:
  - 30
  - 300
  - 1200
workers:
  example_worker:
    type: remote
    scheduler_type: slurm
    work_dir: /path/to/your/scratch/dir
    resources:
    pre_run: |
       source activate automation
    post_run:
    timeout_execute: 120
    max_jobs: 10
    batch:
    host: remote_cluster
    user: username
    port:
    password:
    key_filename: /path/to/key
    passphrase: passphrase
    gateway: ssh nested_server
    forward_agent:
    connect_timeout:
    connect_kwargs:
    inline_ssh_env:
    keepalive: 60
    shell_cmd: bash
    login_shell: true
    interactive_login: true
queue:
  store:
    type: MongoStore
    host: local_machine
    database: automation
    username: username
    password: password
    collection_name: jobs
  flows_collection: flows
  auxiliary_collection: jf_auxiliary
  db_id_prefix:
exec_config: {}
jobstore:
  docs_store:
    type: MongoStore
    database: automation
    host: local_machine
    port: 27017
    username: username
    password: password
    collection_name: outputs
  additional_stores:
    data:
      type: GridFSStore
      database: automation
      host: local_machine
      port: 27017
      username: username
      password: password
      collection_name: outputs_blobs
metadata:
```

Can you spot something suspicious? 👀 

Also this is the error that we get when we want to check the worker:
```
Exception (client): Error reading SSH protocol banner
Traceback (most recent call last):
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/paramiko/transport.py", line 2327, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/paramiko/packet.py", line 381, in readline
    buf += self._read_timeout(timeout)
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/paramiko/packet.py", line 626, in _read_timeout
    raise socket.timeout()
TimeoutError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/paramiko/transport.py", line 2143, in run
    self._check_banner()
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/paramiko/transport.py", line 2331, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

Thank you very much for your help in advance!

**Comment by gpetretto** [comment]
Hi, 
first of all I would suggest using the latest release of jobflow-remote. The interactive branch has been merged a few months ago, so I think it would be better to have also the additional changes that have been added in the meanwhile.

In principle it should be possible to properly configure the gateway in the config file, but I would suggest to first try setting it up in the `~/.ssh/config` file. Fabric should be able to parse it from there and it should be easier and better documented (I typically do this). For example you can add something like this:
```
# Gateway 
Host nested_server
    Hostname nested_server
    User xxx
    IdentityFile ~/.ssh/id_rsa

# cluster 
Host remote_cluster
    Hostname remote_cluster
    User xxx
    ForwardX11 yes
    IdentityFile ~/.ssh/id_rsa
    ProxyJump nested_server
```
And then in the configuration file just set:
```
host: remote_cluster
``` 
and leave all the rest empty.

Would this work for you?

**Comment by QuantumChemist** [comment]
Hi,
Dewen (@DervinSun) will try it. Thank you!

**Comment by DervinSun** [comment]
Hi, 

I have been testing it. It only seems to return the error -- "Name or service not known"

The full details are below

Error while testing worker:
 Traceback (most recent call last):
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/jobflow_remote/config/helper.py", line 160, in check_worker
    host.connect()
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/jobflow_remote/remote/host/remote.py", line 234, in connect
    self.connection.open()
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/fabric/connection.py", line 638, in open
    kwargs["sock"] = self.open_gateway()
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/fabric/connection.py", line 691, in open_gateway
    self.gateway.open()
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/home/users/sundewgy/miniconda3/envs/automation/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The project.yaml has the following settings:

workers:
  automation_worker:
    type: remote
    scheduler_type: slurm
    work_dir: xxxxxxx
    resources:
    pre_run: |
       source activate automation
    post_run:
    timeout_execute: 120
    max_jobs: 10
    batch:
    host: remote-cluster
    user:
    port:
    password:
    key_filename: xxxxxxx
    passphrase: xxxxxxx
    gateway:
    forward_agent:
    connect_timeout:
    connect_kwargs:
    inline_ssh_env:
    keepalive: 60
    shell_cmd: bash
    login_shell: true
    interactive_login: true

and the .ssh/config file has the same setup as yours

Please let me know if you can provide any insight on this

Kind regards
Dewen

**Comment by gpetretto** [comment]
I am sorry, but I never encountered this error.
Does it work if you try to connect to the cluster with `ssh remote-cluster`? 
Also if the key is already specified in the ~/.ssh/config file it should not be necessary to repeat it. Also, for the passphrase it may be good to add it to an ssh agent, instead of hardcoding it in the configuration file (see for example: https://support.ceci-hpc.be/doc/_contents/QuickStart/ConnectingToTheClusters/FromAUnixComputer.html#using-an-ssh-agent-to-avoid-typing-the-passphrase-at-each-login)

**Comment by DervinSun** [comment]
Hi all, 

I am very embarrassed to say this, but the mistake is as always a typo. I mixed up a "_" and a "-" in the .ssh/config. This has been fixed now and it is working now.

I have also implemented the ssh agent thanks to your advice @gpetretto. Thank you so much for the support.

Kind regards
Dewen
