### ISSUE TITLE
Jobs fail with error `Remote error: file path/to/job_dir/remote_job_data.json for job xxx does not exist`

### ISSUE THREAD

**Issue by QuantumChemist** [Matgenix/jobflow-remote#157]
Hey!

so on the weekend we had some network issues and connection to the remote cluster was disrupted. Therefore all the jobs failed with `REMOTE_ERROR` (showing authentication error). Yesterday that problem was fixed and for a few hours, I could run some jobs again. But for whatever reason I can't figure out, in the evening the jobs started to fail with  `Remote error: file path/to/job_dir/remote_job_data.json for job xxx does not exist` and if I copy the file (that only contains "[]" for comparable jobs)  there, it will complain that  `Remote error: file path/to/job_dir/additional_store_data.json for job xxx does not exist` and if I put that file there (which also only contains "[]" for other finished jobs), the job will still fail with `REMOTE_ERROR` saying:
```
│      error = Traceback (most recent call last):                                                                                                         │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/jobflow_remote/jobs/run.py", line 41, in run_remote_job │
│                  in_data = loadfn(IN_FILENAME)                                                                                                          │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/serialization.py", line 82, in loadfn             │
│                  return json.load(fp, *args, **kwargs)                                                                                                  │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/json/__init__.py", line 293, in load                                  │
│                  return loads(fp.read(),                                                                                                                │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/json/__init__.py", line 359, in loads                                 │
│                  return cls(**kw).decode(s)                                                                                                             │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 843, in decode                     │
│                  return self.process_decoded(d)                                                                                                         │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 820, in process_decoded            │
│                  return {                                                                                                                               │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 821, in <dictcomp>                 │
│                  self.process_decoded(k): self.process_decoded(v) for k, v in d.items()                                                                 │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 770, in process_decoded            │
│                  return cls_.from_dict(data)                                                                                                            │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 249, in from_dict                  │
│                  return cls(**decoded)                                                                                                                  │
│                File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/jobflow/core/store.py", line 67, in __init__            │
│                  self.docs_store.key = "uuid"                                                                                                           │
│              AttributeError: 'dict' object has no attribute 'key' 
```
(I anonymized my remote cluster home). So currently, I can neither rerun, nor submit any new jobs, because it runs into the issues mentioned above. I also already tried to setup a fresh conda environment.

Do you have any idea what could be the issue here or any tip what I could try?
Your help is much appreciated!

**Comment by gpetretto** [comment]
Hi @QuantumChemist,

first a quick explanation: jobflow-remote uses a local JobStore to store the output of the Job. The local jobstore contains a maggma Store for each of stires in the original Jobstore (for atomate2 you will have the main job document and the `data` in the `additional_stores`).  
The first guess about this file missing is that the Job was killed during the execution and did not reach the point where it writes it down. Could this be the case? You can check for more hints in the `queue.out` and `queue.err` files.

**Comment by QuantumChemist** [comment]
> Hi @QuantumChemist,
> 
> first a quick explanation: jobflow-remote uses a local JobStore to store the output of the Job. The local jobstore contains a maggma Store for each of stires in the original Jobstore (for atomate2 you will have the main job document and the `data` in the `additional_stores`). The first guess about this file missing is that the Job was killed during the execution and did not reach the point where it writes it down. Could this be the case? You can check for more hints in the `queue.out` and `queue.err` files.

Hi @gpetretto ,

unfortunately my queue.err and queue.out files are completely empty. I usually would look into those files to find out what the problem is.
The strange thing is that for the corresponding job on my local machine I have a `remote_job_data.json ` in ~/.jfremote/auto/tmp/download/path/to/job_dir but it's empty as well.
```
-rw-r--r-- 1 certural domänen-benutzer 1939 Jul 30 11:55 jfremote_out.json
-rw-r--r-- 1 certural domänen-benutzer    0 Jul 30 11:55 remote_job_data.json
```

I cannot say if my job gets killed because usually I'd have a std_err.txt file then in that directory (on the remote cluster) but I only have those files:
```
-rw-r--r-- 1 user 10838 30. Jul 11:54 jfremote_in.json
-rw-r--r-- 1 user  1939 30. Jul 11:55 jfremote_out.json
-rw-r--r-- 1 user     0 30. Jul 11:54 queue.err
-rw-r--r-- 1 user     0 30. Jul 11:54 queue.out
-rw-r--r-- 1 user   785 30. Jul 11:54 submit.sh
```

Could you point me to the code part that would write all the jf remote files on the remote cluster? Sometimes that helps me as well to figure out a solution.

**Comment by gpetretto** [comment]
The `remote_job_data.json` is the file corresponding to the store for the main entry in the JobStore. So they should both be there. But at least the `remote_job_data.json` should not be empty. 

If you did not change the default, the part of the code that writes the file should be entirely in jobflow and maggma.  The jobflow Job is started here: https://github.com/Matgenix/jobflow-remote/blob/499791a2244f32911e66e06068f876fc6b3fd09f/src/jobflow_remote/jobs/run.py#L49. Jobflow will use the passed `store` to do the standard procedure. By default the `JobStore` just contain two maggma `JSONStore`. So the code that writes the files is not directly in jobflow-remote. You can maybe check the content of the `jfremote_out.json` since it is not empty, but maybe it just contains the `start_time`. 
It would rather seem that the Job is not executed at all. In this case the fact that `queue.out` and `queue.err` are empty is quite weird.

**Comment by QuantumChemist** [comment]
> The `remote_job_data.json` is the file corresponding to the store for the main entry in the JobStore. So they should both be there. But at least the `remote_job_data.json` should not be empty.
> 
> If you did not change the default, the part of the code that writes the file should be entirely in jobflow and maggma. The jobflow Job is started here:
> 
> https://github.com/Matgenix/jobflow-remote/blob/499791a2244f32911e66e06068f876fc6b3fd09f/src/jobflow_remote/jobs/run.py#L49
> . Jobflow will use the passed `store` to do the standard procedure. By default the `JobStore` just contain two maggma `JSONStore`. So the code that writes the files is not directly in jobflow-remote. You can maybe check the content of the `jfremote_out.json` since it is not empty, but maybe it just contains the `start_time`.
> It would rather seem that the Job is not executed at all. In this case the fact that `queue.out` and `queue.err` are empty is quite weird.

The `jfremote_out.json` file contains the error messages I put above and the start and end time.

Thank you for showing me the jf remote code line and the explanation. I will try to debug it and see if I can find out what the issue might be.

**Comment by gpetretto** [comment]
ah, I see. I initially thought that the initial error might have been related to the manual addition of the `additional_store_data.json` file. But if you have that error in any case, it looks like that the initial loadfn is not deserializing the `as_dict` of the JSONStore. Maybe something changed in the latest version of monty? which version are you using?

You can try running directly `loadfn("jfremote_in.json")` from the front-end of the node

**Comment by QuantumChemist** [comment]
> ah, I see. I initially thought that the initial error might have been related to the manual addition of the `additional_store_data.json` file. But if you have that error in any case, it looks like that the initial loadfn is not deserializing the `as_dict` of the JSONStore. Maybe something changed in the latest version of monty? which version are you using?
> 
> You can try running directly `loadfn("jfremote_in.json")` from the front-end of the node

For my last jobs that I submitted I tried to downgrade the monty version and the jobs are still pending.I will report back!

**Comment by QuantumChemist** [comment]
Neither downgrading, nor upgrading monty helps.

I used the monty version 2024.5.24 before and today, too (before trying to down- or upgrade). I will try all kinds of versions tomorrow, because now i just randomly picked a version above and below the one I used.

**Comment by QuantumChemist** [comment]
But yeah, I can reproduce the error with ` loadfn("jfremote_in.json")`
```
>>> from monty.serialization import loadfn
>>> loadfn("jfremote_in.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/serialization.py", line 82, in loadfn
    return json.load(fp, *args, **kwargs)
  File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 875, in decode
    return self.process_decoded(d)
  File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 852, in process_decoded
    return {
  File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 853, in <dictcomp>
    self.process_decoded(k): self.process_decoded(v) for k, v in d.items()
  File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 790, in process_decoded
    return cls_.from_dict(data)
  File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/monty/json.py", line 249, in from_dict
    return cls(**decoded)
  File "/home/user-on-remote-cluster/miniconda3/envs/auto/lib/python3.10/site-packages/jobflow/core/store.py", line 67, in __init__
    self.docs_store.key = "uuid"
AttributeError: 'dict' object has no attribute 'key'
>>> 
```
so I will try to find a monty version where it doesn't happen. Thank you for hinting me towards this!

**Comment by QuantumChemist** [comment]
I don't fully understand why that was the solution because I haven't touched the conda env on my remote cluster for ages, but the problem was not monty per se. I had to update the jobflow-remote (I chose the release v0.1.2) version on my remote cluster. Thank you again for helping me and pointing me into the right direction :D

**Comment by DervinSun** [comment]
Hi there, I have also encountered the issue recently, and the scenario is very similar. 

I have my project connected to 2 workers and both workers report back the same remote error. This was also not an issue before. 

The version for jobflow-remote is 0.1.4 and that for monty is 2024.10.21. I have double checked to ensure that the same versions are installed on the workers.

**Comment by QuantumChemist** [comment]
Sometimes it also helps to restart (stop and start) the runner.

**Comment by utf** [comment]
We also encountered this error. If you go to the folder and look at the error or output file from the cluster queue system there is normally a hint. Essentially, we found that something was failing on import before jobflow was starting to run.

In our case it was due to an incompatability with pymatgen and numpy on the runner. Upgrading numpy first, and then all libraries to their most recent versions fixed the issue for us. 

I think the error message is very cryptic in this case and not an accurate representation of the underlying error. I wonder if its possible to catch the case where jobflow was not able to start and report that instead.

**Comment by DervinSun** [comment]
Hi there, 

I just realised what was causing the issue for my case. I have a custom object included in the jobs and it was unable to be de-serialised. 

@QuantumChemist your test with the loadfn("jfremote_in.json") was a really useful hint for my case!

Thank you all so much!

**Comment by QuantumChemist** [comment]
Happy that this could be resolved so quickly :)

**Comment by DervinSun** [comment]
It actually took me 3 days! I have reinstalled the setup on all three machines before seeing your test that reproduced the error on the worker machine. 😂

Maybe it could be a good idea to include a type checker to enforce a MSONable object to be submitted, or find a way to forward the MSONError to the error message in Job info?

**Comment by gpetretto** [comment]
Great seeing that you figured it out.

As for the error I totally agree that this is not clear enough and should be made easier to identify.

> I think the error message is very cryptic in this case and not an accurate representation of the underlying error. I wonder if its possible to catch the case where jobflow was not able to start and report that instead.

It may be possible to do that. I think this may also be related to issues in the pre_run reported here #220.

Just to be sure, do I understand correctly that in all your cases the problem was that jobflow-remote started on the cluster but stopped before being able to create the `remote_job_data.json` file?
I think that the easiest and first step would be to create this file as soon as the job starts. So that at least it will not report this "fake" error, logging directly the correct problem. Then maybe also always download the queue.out and queue.err file (assuming that this will be a small overhead) and store their content in the job document if there is the job fails? (or always?)
One more step could be adding some `echo`s in the submission script, to split the different section, so that jobflow-remote should be able to tell at which point the script failed and directly provide some additional information about the error.
Any comment?
