### ISSUE TITLE
List of flows by state does not work

### ISSUE THREAD

**Issue by davidwaroquiers** [Matgenix/jobflow-remote#16]
It seems that the jf flow list -s SOMESTATE does not work. I will try to investigate.

**Comment by gpetretto** [comment]
Seems to work in my case. Could it be that you were trying to filter based on the remote state? in that case the `-rs` option should be used

**Comment by davidwaroquiers** [comment]
No it's Marco who is trying to filter based on COMPLETED flows and it gives all flows (most, if not all are FAILED). Is there anything that might have changed in latest versions ?

**Comment by gpetretto** [comment]
I am not sure if anything relevant changed in the meanwhile. Before trying to debug it is probably worth trying to create a new enviroment with the latest git version and see if the error persists.

**Comment by gpetretto** [comment]
Sorry, I had completely misunderstood the context and I was trying the `jf job list` command.
