### ISSUE TITLE
Add  `--query` (or `--worker`) flag to `jf job rerun/retry`

### ISSUE THREAD

**Issue by janosh** [Matgenix/jobflow-remote#170]
i would like to rerun jobs selectively by worker. this reruns/retries _all_ jobs:

```sh
jf --project <proj-name> job retry --state REMOTE_ERROR
jf --project <proj-name> job rerun --state FAILED
```

there's the `--metadata` flag but that only allows filtering by `job.metadata.<any-sub-key>` (which in my case is an empty dict for all jobs across multiple workers). how about renaming `--metadata` to `--query` (as in `fireworks`) to allow filtering by any document key?

**Comment by gpetretto** [comment]
I think being able to query by worker or with a generic query is reasonable. However, I would leave the `--metadata` option, since this was an explicit request from a customer.
We can add the `--query` and `--worker` options for the job operations in the CLI.
