### ISSUE TITLE
Support for heterogeneous computing resources?

### ISSUE THREAD

**Issue by orionarcher** [Matgenix/jobflow-remote#184]
I'd like to submit flows where some jobs are GPU heavy and some are CPU heavy. For example, generate a MLFF MD trajectory and then calculate RDFs from it. Is there current or planned support for flows with heterogenous computing resources?

e.g. 

```python
heterogenous_flow = Flow([gpu_job, cpu_job])
submit_flow(my_flow, worker=collection_of_workers)
```

**Comment by gpetretto** [comment]
Hi @orionarcher,
I am not entirely sure if this what you would like to have, and it is a bit more involved, but un principle this should be already possible. For example with something like this
```python
heterogenous_flow = Flow([gpu_job, cpu_job])
heterogenous_flow = set_run_config(heterogenous_flow, name_filter="GPU_JOB_NAME", worker="gpu_worker")
submit_flow(heterogenous_flow, worker="cpu_worker")
```
Here is the documentation explaining this a bit more in detail: https://matgenix.github.io/jobflow-remote/user/tuning.html#how-to-tune
Would this work for you? Or do you need something different?

**Comment by orionarcher** [comment]
This looks like it will work for me, thank you! I'll reopen the issue if I have any trouble.
