### ISSUE TITLE
Flow information

### ISSUE THREAD

**Issue by davidwaroquiers** [Matgenix/jobflow-remote#19]
It would be good to be able to get information about the steps of a given flow. Something like a "jf flow info" that would give information of parents of a given waiting job. @marcodigennaro was asking how to know which other job a given job is WAITING for and I think it would be a very legitimate query from a user. I think we should wait for the new queue implementation before trying to implement this though. Any thoughts @gpetretto and @utf ?

**Comment by davidwaroquiers** [comment]
Getting the parents would actually be relatively easy from the db_id. Following script is working:

```
from jobflow_remote.jobs.jobcontroller import JobController

def get_parents(db_id):
    jc = JobController(project_name='someproject')
    wf = jc.rlpad.lpad.get_wf_by_fw_id_lzyfw(db_id)
    parents = []
    for some_possible_parent_id, dependent_fw_ids in wf.links.items():
        if db_id in dependent_fw_ids:
            parents.append(some_possible_parent_id)
    return parents

print(get_parents(db_id=1))
```

**Comment by gpetretto** [comment]
`jf flow info` is definitely in the todo list. At the moment there is no way to even see the ids of all the jobs belonging to a flow.  I will try to add it soon.
It seems that the list of parents for a specific job would be more suitable in a `jf job parents` instead. What do you think?
In principle, if a graphical representation of the flow is implemented it could also do the job.

**Comment by davidwaroquiers** [comment]
Maybe I would not add a jf job parents but an option to jf job info, e.g.  jf job info DB_ID --parents (and -p). What do you think ? For the flow info, it might also be from a -vvv something perspective. If you pass more verbose, then you can see all the jobs and their dependencies (in text, not graphically). What do you think ?

**Comment by gpetretto** [comment]
It is a possibility. The query would also need to fetch the flow, so indeed should be only returned optionally.

**Comment by marcodigennaro** [comment]
Initially the problem was how to detect all the parents which were FAILED whose childs were WAITING. 
Practically I wanted the child jobs to be killed automatically once the parents were dying. 

We discussed with @davidwaroquiers on need to have a "physical" error - (eg an impossible electronic configuration, or a too small unit cell) and a "technical" error (eg time or memory limit). I point this out here since the first flow (physical error) should kill all children, while the technical error should allow for inspection and resubmission of a single job.

**Comment by davidwaroquiers** [comment]
This is not something jobflow-remote should deal with (distinction between physical and technical error), but rather either the implementation of the workflow in whichever workflow library (e.g. atomate2 or custom) or the user himself.

**Comment by davidwaroquiers** [comment]
Was there any update on this ? @gpetretto

**Comment by davidwaroquiers** [comment]
I think this can be closed @gpetretto ?

**Comment by gpetretto** [comment]
I think so. `jf flow info` is implemented and also `jf flow graph` can be useful in this respect.
