### ISSUE TITLE
how to rerun a job but with improved memory

### ISSUE THREAD

**Issue by yw-fang** [Matgenix/jobflow-remote#198]
Hi, all

We can rerun a failed job by uuid. If the job rerun was successful and the database would be updated.

I had a vasp job terminated in the remote HPC, the only information about error was shown below:
```
srun: error: nid002485: tasks 0-19: Terminated
srun: Terminating StepId=8207865.0
srun: Force Terminated StepId=8207865.0
```
 and all the other VASP output files such as OUTCAR and OSZICAR did not report any errors.

I could revise the memory in the slurm job script submit.sh and "sbatch submit.sh" in the remote HPC manually. It was ended as expected (but the updated data was not stored in the database in my local computer).

To make the rerun job be updated in the local database, I could revise the memory information directly before I rerun. In this case, the memory in the newly generated submit.sh will be changed. 

Is there any built-in method in jobflow-remote so that we can revise the amount of the memory used to run the jobs (especially if we have many failed jobs to be rerun)? Thank you very much!

**Comment by gpetretto** [comment]
Hi @yw-fang,
it is possible to change the allocated memory by changing the resources associated to a job using the CLI. See here for some documentation: https://matgenix.github.io/jobflow-remote/user/tuning.html#cli
In your case, you would need to use the `jf job set resources`, you can check the standard `jf job set resources -h` for the details. An example would be 
```
jf job set resources -did DB_ID_OF_THE_JOB '{"mem": 64000}'
```

**Comment by yw-fang** [comment]
Hello, @gpetretto, that's fantastic! Thanks very much for bringing my attention to it. If I'm not wrong, the keys that can be used to change the resources are in line with the keys used in the database?

**Comment by gpetretto** [comment]
Sorry @yw-fang, I missed your follow-up question. I am not sure if I got it correctly though.
If you are referring to the keys that can be set with `jf job set resources`, those are the same that can be used in the `resources` argument of `submit_flow`. See the [documentation](https://matgenix.github.io/jobflow-remote/user/tuning.html#resources) and linked templates from qtoolkit.

**Comment by yw-fang** [comment]
> Sorry @yw-fang, I missed your follow-up question. I am not sure if I got it correctly though. If you are referring to the keys that can be set with `jf job set resources`, those are the same that can be used in the `resources` argument of `submit_flow`. See the [documentation](https://matgenix.github.io/jobflow-remote/user/tuning.html#resources) and linked templates from qtoolkit.

This is the answer to my question! Thanks very much for your response and for bringing my attention to qtoolkit
