### ISSUE TITLE
Full-split : Remote Runner setup

### ISSUE THREAD

**Issue by DervinSun** [Matgenix/jobflow-remote#214]
I didn't quite find much explanation for this point on the documentations. How would I set up a remote runner on a different machine in a full-split setup? 

Is there a specific runner option that I need to change?

**Comment by gpetretto** [comment]
Hi @DervinSun,

there is no particular option that needs to be set in the runner. It just means that at least some of the workers are of `type: remote`. There is also no configuration that needs to be done on the worker machine either, but the python environment should be equivalent to the one on the runner machine.

Does this answer your question?

**Comment by DervinSun** [comment]
So if I put in "jf runner start", it will automatically start the runner on the server?

**Comment by gpetretto** [comment]
I am not sure which machine you are referring to with the "server". 
The Runner needs to be executed only on one machine (and not more than one), that is responsible to manage the execution of the Jobs by sending them to the workers. Maybe this part of the documentation may help clarify the point: https://matgenix.github.io/jobflow-remote/user/introduction.html#working-principles
`jf runner start` will start the runner on the machine where you execute the command. This will start a daemon locally. If you have a `remote` worker (e.g. a cluster) this will submit your jobs there on its own, so nothing needs to be executed manually on the worker, aside from the set up.
Does this help clarifying the procedure?

**Comment by DervinSun** [comment]
Sorry, for not being very clear. When I said "server" I mean the machine that have the runner. So if I understand correctly, as long as I have a runner start on one machine, I do not need to run the "jf runner start" command on any other machine. It will just work?
Let me give it a try, which should probably help me understand.

**Comment by gpetretto** [comment]
> So if I understand correctly, as long as I have a runner start on one machine, I do not need to run the "jf runner start" command on any other machine. 

Yes

> It will just work? 

As long as everything is propely configured, it should indeed work just like that 😃
