### ISSUE TITLE
`jf admin upgrade` causes a lot of errors

### ISSUE THREAD

**Issue by FabiPi3** [Matgenix/jobflow-remote#224]
Basically not using the `test_version_upgrade` option isn't working.

The following `parse_version` call on the `None` value gives a TypeError.

And in the following calls to `dry_run` and `upgrade` the test version is used instead of the actual target version.

Do I misunderstand the use of this command?

I am referring the up-to-date master branch.

**Comment by gpetretto** [comment]
This should be the same issue as in #211. Closing as a duplicate, but feel free to reopen if the proposed solution does not solve the problem.
