### ISSUE TITLE
Suggestion: improve -sdate option

### ISSUE THREAD

**Issue by marcodigennaro** [Matgenix/jobflow-remote#24]
I often need to check all the jobs submitted today, or in the last hour. 
I would suggest to insert `TODAY` as an option and eventually also to set the last hour as default since there is none.

**Comment by gpetretto** [comment]
By default `jf job list` should return only the latest 100 jobs according to the last time the job was modified. This can be increased or decreased with the `-m` option
Other options are available to filter based on time of last modification:
* ```
  jf job list -ds 2
  ```
  will print the jobs modified in the last two days.
* ```
  jf job list -sdate 2023-09-01 -edate 2023-09-10
  ```
  will print the jobs last modified from September 1st to 10th. It can also be `-sdate 2023-09-05T19:00:00` to specify the time.
Full list of options with `jf job list -h`.

Do you think this would be enough? Would it be better to also have a `--hours` option for jobs modified in the last N hours?

**Comment by marcodigennaro** [comment]
`jf job list -ds 1` gives back the last 24 hours (so many jobs are from yesterday).
The `--hours` is a nice idea. 
Another alternative would be to specify only the hours in the current `-sdate` option and allow the `%H:%M:%S'`  format only, with the implicit assumption of `%Y-%m-%d'` being today

**Comment by gpetretto** [comment]
Pushed a change that should allow both these options (hours and specify only an hour of the current day): https://github.com/Matgenix/jobflow-remote/commit/7bcd12e43c366dada43a125d591cf0187611479f.
Can you test and let me know if this solves your issue?

**Comment by marcodigennaro** [comment]
It works! Thanks

**Comment by davidwaroquiers** [comment]
Just commenting on this issue, supposing it's 10 past midnight and I put -sdate 23:00:00, it would be nice to show things in the last 1h10m. What do you think ? (so the assumption is not exactly TODAY's date, but last corresponding time in the last 24 hours).

**Comment by marcodigennaro** [comment]
To my understanding, in your case `--hours 2` gives the last 2 hours and `-ds 1` gives the last 24 hours.
`TODAY` is not implemented at this stage, but it is equivalent to `-sdate '00:00:00'`

**Comment by davidwaroquiers** [comment]
Yes I undestood that TODAY's was not implemented. Indeed --hours can be used to see things in the last N hours. I was thinking about -sdate 19:30:00 which would be "last time since last 19h30". I think as it is now, if it is between 19h30 and 23h59, it will work fine, once it is 00h01 (next day), it will return nothing.

**Comment by davidwaroquiers** [comment]
Anyway it's just a detail, @gpetretto if you think it's not worth (and/or tedious to implement), just close the issue again :)

**Comment by gpetretto** [comment]
done in https://github.com/Matgenix/jobflow-remote/commit/c77029c85ed776a6487446d899deada549b0132c
