### ISSUE TITLE
Jobflow dependency

### ISSUE THREAD

**Issue by davidwaroquiers** [Matgenix/jobflow-remote#30]
I think we could now use the official jobflow repo. Or should we wait (e.g. because of pydantic v2 ?).

https://github.com/Matgenix/jobflow-remote/blob/92f9a570fa18da9470248993fd855efcd778d296/pyproject.toml#L29

**Comment by gpetretto** [comment]
Indeed with the latest jobflow release (0.1.14) it will be broken if #29 is not merged, as jobflow-remote will require pydantic<2 to work.
In case we should pin jobflow==0.1.13.
