### ISSUE TITLE
'REMOTE_ERROR' state for running job

### ISSUE THREAD

**Issue by marcodigennaro** [Matgenix/jobflow-remote#36]
The mongodb has crashed on my WS.
A bunch of jobs were running and have been set to remote_state = 'FAILED'  and   state = 'REMOTE_ERROR' while they are still running fine on the runner. 
The FW.json file contains remote.state = "CHECKED_OUT" and "state": "RESERVED".

<img width="1229" alt="image" src="https://github.com/Matgenix/jobflow-remote/assets/21054239/9ace76b1-3929-42f0-bdf2-57d70708c92a">

<img width="1428" alt="image" src="https://github.com/Matgenix/jobflow-remote/assets/21054239/7b93d9d8-dd10-4d2a-9fff-98be191e0a60">

Is there any way to set them back to 'RUNNING'? Some of them have been running for 7 days now.

**Comment by davidwaroquiers** [comment]
> The mongodb has crashed on my WS.
> A bunch of jobs were running and have been set to remote_state = 'FAILED'  and   state = 'REMOTE_ERROR' while they are still running fine on the runner. 
> The FW.json file contains remote.state = "CHECKED_OUT" and "state": "RESERVED".
> 
> <img width="1229" alt="image" src="https://github.com/Matgenix/jobflow-remote/assets/21054239/9ace76b1-3929-42f0-bdf2-57d70708c92a">
> 
> <img width="1428" alt="image" src="https://github.com/Matgenix/jobflow-remote/assets/21054239/7b93d9d8-dd10-4d2a-9fff-98be191e0a60">
> 
> Is there any way to set them back to 'RUNNING'? Some of them have been running for 7 days now. 
> 

Hi Marco,


Yes there is. I think it is "jf set-remote-state" command. I'let @gpetretto confirm and help you on this as I am on departure.


Best

**Comment by gpetretto** [comment]
In this conditions (i.e. `remote_state="FAILED"`. and `remote_previous_state="RUNNING"`) you can run `jf job reset-failed 20511`. This should put back the jobs to the `ONGOING [RUNNING]` state. At this point this can be done only on one job at the time with the CLI. The same function is exposed in the `JobController.reset_failed_state()` method if this could help. 
I would suggest to try to apply to one job first and check that everythig works correctly before proceeding with the other jobs.

One question though: how did the Jobs end up in that condition? If the DB was down in principle it should have not been possible to even change their state to FAILED. Could it be that the queue manager on the cluster was being unresponsive? Can you run a `jf job info -err 20551` for a couple of the failed job to see where the error is coming from?

**Comment by marcodigennaro** [comment]
Good point about the cluster. I have no idea... I am trying to investigate already why has the mongodb crashed.
In the meanwhile, these are the results of the queue

![image](https://github.com/Matgenix/jobflow-remote/assets/21054239/69a804a8-e363-4b9f-b265-05d8137e7d4c)

![image](https://github.com/Matgenix/jobflow-remote/assets/21054239/9d33046d-feb2-40a1-9606-0214034bb248)

**Comment by marcodigennaro** [comment]
These are the states from the FW.json
I haven't reset the failed job yet in case you would like to have more info

![image](https://github.com/Matgenix/jobflow-remote/assets/21054239/fe447d4f-b735-4328-b643-abc0e1d440f7)

Thanks a lot

**Comment by marcodigennaro** [comment]
it worked
