### ISSUE TITLE
Error during retry

### ISSUE THREAD

**Issue by utf** [Matgenix/jobflow-remote#40]
I had a job that errored during checkout.

I retried the job with 

```
> jf job retry 1
The selected project is val from config file /home/alex/.jfremote/val.yaml
Operation completed: 1 jobs modified
```

However, when I then checked the status of the job I see:

```
> jf job info 1
The selected project is val from config file /home/alex/.jfremote/val.yaml
An Error occurred during the command execution: KeyError 'retry_time_limit'
```

A few seconds later I tried again, and this error disappeared and the job state appeared like normal.

**Comment by gpetretto** [comment]
Likely a bug here. I will try to reproduce it. 
Just to clarify, do you maybe remember if the error was during checkout, or the job was CHECKED_OUT, so the error was in the subsequent step (i.e. upload)?

**Comment by utf** [comment]
I think you can reproduce it by specifying a worker for which the configuration doesn't exist. The job state is `REMOTE_ERROR`. The error has actually came back after a second retry and hasn't gone away.

**Comment by gpetretto** [comment]
I should have fixed it. I introduced it in one of the latest updates.
Can you please pull the latest commits to confirm it?

**Comment by utf** [comment]
That fixed it! Thank you
