### ISSUE TITLE
Add tests for `Job`s with a function arg or kwarg

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Matgenix/jobflow-remote#45]
See discussion in #44. Just opening this as a separate issue so [@davidwaroquiers' comment](https://github.com/Matgenix/jobflow-remote/issues/44#issuecomment-1853445067) doesn't get lost.

**Comment by ml-evs** [comment]
Whoops, didn't see this other issue. I think my PR #51 should close this for you @Andrew-S-Rosen? The only thing that came up is the standard caveat that the function arg must be importable and cannot be e.g., a `lambda`. Feel free to reopen if my test case isn't sufficient!
