### ISSUE TITLE
Multiple lines to `pre_run`

### ISSUE THREAD

**Issue by naik-aakash** [Matgenix/jobflow-remote#61]
Is there any way one can have multiple lines to `pre_run` in `ExecutionConfig` ? I see currently, datatype supported is string only. 
Will using `\n` as seperator work ?

**Comment by gpetretto** [comment]
Hi @naik-aakash,

yes, using a single string with `\n` works:
```yaml
pre_run: "echo 'one line'\necho 'another line'"
```
In principle any way of defining a[ multiline string with yaml](https://yaml-multiline.info/) should work as well. For example:

```yaml
pre_run: |
  echo 'one line'
  echo 'another line'
```
should work as well.

**Comment by naik-aakash** [comment]
Great! Thanks @gpetretto ! I will check it out in sometime

**Comment by naik-aakash** [comment]
closing this as the solution provided works fine.
