### ISSUE TITLE
Queue-out interactive mode

### ISSUE THREAD

**Issue by JaGeo** [Matgenix/jobflow-remote#90]
I am now using jobflow-remote successfully in the interactive mode. However, the queue-out option of jobs does not work. It never asks me to login or cannot use the existing connection. It even crashes then in such a way that my terminal becomes unusable and I have to open a new one (freezes).

In contrast `job info` works without any issue.

**Comment by gpetretto** [comment]
Thanks for reporting this. Do you have the issue even with the latest change to the branch (https://github.com/Matgenix/jobflow-remote/commit/62181dbe9d1d317be60beee48fdb7e27226c7640)? 

Just to clarify: the CLI does not have access to the connection opened by the runner, so you need a new one every time you run a command in the CLI that needs to connect to the worker. This happens in the case of the queue-out, as it fetches the files directly from the job directory. `job info` just interacts with the DB. 

In principle the last change should have made `job job queue-out` similar to `jf project check`. Can you tell me if `jf project check -w YOUR_MFA_WORKER_NAME` works for you?

**Comment by JaGeo** [comment]
`jf -p lobster project check -w supermuc_worker` works for me. 

I would prefer to not install yet another version this and next week. I am happy that the other things are working now. I will need that environment (working) for next week.

**Comment by gpetretto** [comment]
Good. I should have replicated the same behaviour in `jf job queue-out`, so it should hopefully work for you as well (when/if you will have the chance to install yet another version 😄 ). Thanks for all the testing.

The problematic part is the spinner in the CLI, that should be explicitly disabled when a prompt from the user is required. I need to check if there is a better way than explcitly adding an `if` after manually discovering cases where it fails.

**Comment by JaGeo** [comment]
Thank you! Will check soon!

**Comment by gpetretto** [comment]
I will close this issue as it should hopefully have been fixed in the released version including the interactive mode. Let me know if the problem shows up again.
