### ISSUE TITLE
Missing docs: batch mode

### ISSUE THREAD

**Issue by ml-evs** [Matgenix/jobflow-remote#96]
Just raising an issue about the batch mode, which is not documented. In fact, the batch config model is just serving the docstring for `BaseModel` at https://matgenix.github.io/jobflow-remote/api/jobflow_remote.config.base.html#jobflow_remote.config.base.BatchConfig so it is very well hidden.

**Comment by gpetretto** [comment]
The batch submission is now documented in the "Advanced options": https://matgenix.github.io/jobflow-remote/user/advancedoptions.html#batch-submission. I also added a small description in the docstrings https://matgenix.github.io/jobflow-remote/api/jobflow_remote.config.base.html#jobflow_remote.config.base.BatchConfig. Do you think this is enough?
